---
name: Build Pipeline

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: clusdoc@docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: wearelumenai/clusdoc/clusdoc
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          dockerfile: build/Dockerfile
          tag_semver: true
          buildoptions: "--compress"
